import { SessionProvider } from "next-auth/react";
import './globals.css'
import { Inter } from 'next/font/google'
import NavBar from "@/components/NavBar";
import { NextAuthProvider } from "./Provider";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          <NavBar />
          {children}
        </NextAuthProvider>
      </body>
    </html>
  )
}
